//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.20 at 12:19:36 PM CET 
//


package iristk.xml._package;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iristk.xml._package package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iristk.xml._package
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link Package.Services }
     * 
     */
    public Package.Services createPackageServices() {
        return new Package.Services();
    }

    /**
     * Create an instance of {@link Package.Classpath }
     * 
     */
    public Package.Classpath createPackageClasspath() {
        return new Package.Classpath();
    }

    /**
     * Create an instance of {@link Package.Provide }
     * 
     */
    public Package.Provide createPackageProvide() {
        return new Package.Provide();
    }

    /**
     * Create an instance of {@link Package.Run }
     * 
     */
    public Package.Run createPackageRun() {
        return new Package.Run();
    }

    /**
     * Create an instance of {@link Package.Services.Service }
     * 
     */
    public Package.Services.Service createPackageServicesService() {
        return new Package.Services.Service();
    }

    /**
     * Create an instance of {@link Package.Classpath.Lib }
     * 
     */
    public Package.Classpath.Lib createPackageClasspathLib() {
        return new Package.Classpath.Lib();
    }

    /**
     * Create an instance of {@link Package.Classpath.Src }
     * 
     */
    public Package.Classpath.Src createPackageClasspathSrc() {
        return new Package.Classpath.Src();
    }

    /**
     * Create an instance of {@link Package.Classpath.Dll }
     * 
     */
    public Package.Classpath.Dll createPackageClasspathDll() {
        return new Package.Classpath.Dll();
    }

    /**
     * Create an instance of {@link Package.Provide.Class }
     * 
     */
    public Package.Provide.Class createPackageProvideClass() {
        return new Package.Provide.Class();
    }

    /**
     * Create an instance of {@link Package.Run.Command }
     * 
     */
    public Package.Run.Command createPackageRunCommand() {
        return new Package.Run.Command();
    }

}
