//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.16 at 08:54:18 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2001/06/grammar", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package iristk.xml.srgs;
