/*******************************************************************************
 * Copyright (c) 2014 Gabriel Skantze.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/gpl.html
 * 
 * Contributors:
 *     Gabriel Skantze - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.02 at 09:46:39 AM CEST 
//


package iristk.speech.nuance9.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="mode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="instance">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SWI_literal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SWI_grammarName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SWI_meaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SWI_literalTimings">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="alignment">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{}word" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="unit_msecs" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="grammar" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="conf" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "text",
    "instance"
})
@XmlRootElement(name = "interpretation")
public class Interpretation {

    @XmlElement(required = true)
    protected Interpretation.Text text;
    @XmlElement(required = true)
    protected Interpretation.Instance instance;
    @XmlAttribute(name = "conf")
    protected Float conf;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretation.Text }
     *     
     */
    public Interpretation.Text getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretation.Text }
     *     
     */
    public void setText(Interpretation.Text value) {
        this.text = value;
    }

    /**
     * Gets the value of the instance property.
     * 
     * @return
     *     possible object is
     *     {@link Interpretation.Instance }
     *     
     */
    public Interpretation.Instance getInstance() {
        return instance;
    }

    /**
     * Sets the value of the instance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpretation.Instance }
     *     
     */
    public void setInstance(Interpretation.Instance value) {
        this.instance = value;
    }

    /**
     * Gets the value of the conf property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getConf() {
        return conf;
    }

    /**
     * Sets the value of the conf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setConf(Float value) {
        this.conf = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SWI_literal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SWI_grammarName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SWI_meaning" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SWI_literalTimings">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="alignment">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{}word" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="unit_msecs" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="grammar" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "swiLiteral",
        "swiGrammarName",
        "swiMeaning",
        "swiLiteralTimings"
    })
    public static class Instance {

        @XmlElement(name = "SWI_literal", required = true)
        protected String swiLiteral;
        @XmlElement(name = "SWI_grammarName", required = true)
        protected String swiGrammarName;
        @XmlElement(name = "SWI_meaning", required = true)
        protected String swiMeaning;
        @XmlElement(name = "SWI_literalTimings", required = true)
        protected Interpretation.Instance.SWILiteralTimings swiLiteralTimings;
        @XmlAttribute(name = "grammar")
        protected String grammar;

        /**
         * Gets the value of the swiLiteral property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSWILiteral() {
            return swiLiteral;
        }

        /**
         * Sets the value of the swiLiteral property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSWILiteral(String value) {
            this.swiLiteral = value;
        }

        /**
         * Gets the value of the swiGrammarName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSWIGrammarName() {
            return swiGrammarName;
        }

        /**
         * Sets the value of the swiGrammarName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSWIGrammarName(String value) {
            this.swiGrammarName = value;
        }

        /**
         * Gets the value of the swiMeaning property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSWIMeaning() {
            return swiMeaning;
        }

        /**
         * Sets the value of the swiMeaning property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSWIMeaning(String value) {
            this.swiMeaning = value;
        }

        /**
         * Gets the value of the swiLiteralTimings property.
         * 
         * @return
         *     possible object is
         *     {@link Interpretation.Instance.SWILiteralTimings }
         *     
         */
        public Interpretation.Instance.SWILiteralTimings getSWILiteralTimings() {
            return swiLiteralTimings;
        }

        /**
         * Sets the value of the swiLiteralTimings property.
         * 
         * @param value
         *     allowed object is
         *     {@link Interpretation.Instance.SWILiteralTimings }
         *     
         */
        public void setSWILiteralTimings(Interpretation.Instance.SWILiteralTimings value) {
            this.swiLiteralTimings = value;
        }

        /**
         * Gets the value of the grammar property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGrammar() {
            return grammar;
        }

        /**
         * Sets the value of the grammar property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGrammar(String value) {
            this.grammar = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="alignment">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{}word" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="unit_msecs" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "alignment"
        })
        public static class SWILiteralTimings {

            @XmlElement(required = true)
            protected Interpretation.Instance.SWILiteralTimings.Alignment alignment;

            /**
             * Gets the value of the alignment property.
             * 
             * @return
             *     possible object is
             *     {@link Interpretation.Instance.SWILiteralTimings.Alignment }
             *     
             */
            public Interpretation.Instance.SWILiteralTimings.Alignment getAlignment() {
                return alignment;
            }

            /**
             * Sets the value of the alignment property.
             * 
             * @param value
             *     allowed object is
             *     {@link Interpretation.Instance.SWILiteralTimings.Alignment }
             *     
             */
            public void setAlignment(Interpretation.Instance.SWILiteralTimings.Alignment value) {
                this.alignment = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{}word" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="unit_msecs" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "word"
            })
            public static class Alignment {

                protected List<Word> word;
                @XmlAttribute(name = "type")
                protected String type;
                @XmlAttribute(name = "unit_msecs")
                protected Integer unitMsecs;

                /**
                 * Gets the value of the word property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the word property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getWord().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Word }
                 * 
                 * 
                 */
                public List<Word> getWord() {
                    if (word == null) {
                        word = new ArrayList<Word>();
                    }
                    return this.word;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the unitMsecs property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getUnitMsecs() {
                    return unitMsecs;
                }

                /**
                 * Sets the value of the unitMsecs property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setUnitMsecs(Integer value) {
                    this.unitMsecs = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="mode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Text {

        @XmlValue
        protected String content;
        @XmlAttribute(name = "mode")
        protected String mode;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

    }

}
