/*******************************************************************************
 * Copyright (c) 2014 Gabriel Skantze.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/gpl.html
 * 
 * Contributors:
 *     Gabriel Skantze - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.02 at 09:46:39 AM CEST 
//


package iristk.speech.nuance9.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iristk.speech.nuance9.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iristk.speech.nuance9.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Interpretation }
     * 
     */
    public Interpretation createInterpretation() {
        return new Interpretation();
    }

    /**
     * Create an instance of {@link Interpretation.Instance }
     * 
     */
    public Interpretation.Instance createInterpretationInstance() {
        return new Interpretation.Instance();
    }

    /**
     * Create an instance of {@link Interpretation.Instance.SWILiteralTimings }
     * 
     */
    public Interpretation.Instance.SWILiteralTimings createInterpretationInstanceSWILiteralTimings() {
        return new Interpretation.Instance.SWILiteralTimings();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Interpretation.Text }
     * 
     */
    public Interpretation.Text createInterpretationText() {
        return new Interpretation.Text();
    }

    /**
     * Create an instance of {@link Word }
     * 
     */
    public Word createWord() {
        return new Word();
    }

    /**
     * Create an instance of {@link Interpretation.Instance.SWILiteralTimings.Alignment }
     * 
     */
    public Interpretation.Instance.SWILiteralTimings.Alignment createInterpretationInstanceSWILiteralTimingsAlignment() {
        return new Interpretation.Instance.SWILiteralTimings.Alignment();
    }

}
